repository_type: pipeline

nf_core_version: "4.1.0"

lint:
  merge_markers: false
  actions_nf_test: false
  files_unchanged:
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/workflows/branch.yml
    - .github/workflows/linting_comment.yml
    - .github/workflows/linting.yml
    - .github/.dockstore.yml
    - docs/CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-pangenomesv_logo_light.png
    - docs/images/nf-core-pangenomesv_logo_light.png
    - docs/images/nf-core-pangenomesv_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - assets/email_template.html
    - assets/email_template.txt
    - docs/README.md
    - .gitignore
    - LICENSE
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
  files_exist:
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/ISSUE_TEMPLATE/feature_request.yml
    - .github/PULL_REQUEST_TEMPLATE.md
    - .github/.dockstore.yml
    - docs/CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - assets/nf-core-pangenomesv_logo_light.png
    - docs/images/nf-core-pangenomesv_logo_light.png
    - docs/images/nf-core-pangenomesv_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
    - conf/igenomes_ignored.config
    - conf/test_full.config
    - tests/default.nf.test
    - .github/workflows/pr-comment.yml
  readme:
    - nextflow_badge

template:
  org: medbioinf
  name: pangenomesv
  description: Pipeline for population-level structural variant characterization using
    pangenome graphs
  author: Jonah Kapski
  version: 1.0.0dev
  force: true
  outdir: /home/ubuntu/medbioinf-wf-structural-variants
  skip_features:
    - github
    - igenomes
    - fastqc
    - codespaces
    - vscode
  is_nfcore: false
